module.exports = {
    "locations": {
        "biscayne ave": {
            "type": "property",
            "group": 0,
            "rent": [11, 55, 160, 475, 650, 800, 1300],
            "mortgage": 75,
            "house": 50,
            "forward": ["short line"],
            "backward": ["miami ave"],
            "side": [3],
            "track": [0],
            "below": ["pennsylvania ave"]
        },
        "miami ave": {
            "type": "property",
            "group": 0,
            "rent": [9, 45, 120, 350, 500, 700, 1200],
            "mortgage": 65,
            "house": 50,
            "forward": ["biscayne ave"],
            "backward": ["holland tunnel ne"],
            "side": [3],
            "track": [0],
            "below": ["misfortune middle east"]
        },
        "florida ave": {
            "type": "property",
            "group": 0,
            "rent": [9, 45, 120, 350, 500, 700, 1200],
            "mortgage": 65,
            "house": 50,
            "forward": ["holland tunnel ne"],
            "backward": ["fortune inner ne"],
            "side": [2],
            "track": [0],
            "below": ["ventnor ave"]
        },
        "lombard st": {
            "type": "property",
            "group": 1,
            "rent": [17, 85, 240, 475, 670, 1025, 1525],
            "mortgage": 105,
            "house": 100,
            "forward": ["squeeze play"],
            "backward": ["reverse"],
            "side": [3],
            "track": [0],
            "below": ["park pl"]
        },
        "the embarcadero": {
            "type": "property",
            "group": 1,
            "rent": [17, 85, 240, 475, 670, 1025, 1525],
            "mortgage": 105,
            "house": 100,
            "forward": ["fisherman's wharf"],
            "backward": ["squeeze play"],
            "side": [0],
            "track": [0],
            "below": ["baltic ave"]
        },
        "fisherman's wharf": {
            "type": "property",
            "group": 1,
            "rent": [21, 105, 320, 780, 950, 1125, 1625],
            "mortgage": 125,
            "house": 100,
            "forward": ["telephone company"],
            "backward": ["the embarcadero"],
            "side": [0],
            "track": [0],
            "below": ["income tax"]
        },
        "beacon st": {
            "type": "property",
            "group": 2,
            "rent": [30, 160, 470, 1050, 1250, 1500, 2500],
            "mortgage": 165,
            "house": 200,
            "forward": ["bonus"],
            "backward": ["misfortune inner sw"],
            "side": [0],
            "track": [0],
            "below": ["fortune middle south"]
        },
        "boylston st": {
            "type": "property",
            "group": 2,
            "rent": [30, 160, 470, 1050, 1250, 1500, 2500],
            "mortgage": 165,
            "house": 200,
            "forward": ["newbury st"],
            "side": [1],
            "backward": ["bonus"],
            "track": [0],
            "below": ["states ave"]
        },
        "newbury st": {
            "type": "property",
            "group": 2,
            "rent": [40, 185, 550, 1200, 1500, 1700, 2700],
            "mortgage": 190,
            "house": 200,
            "forward": ["pennsylvania railroad"],
            "backward": ["boylston st"],
            "side": [1],
            "track": [0],
            "below": ["virginia ave"]
        },
        "fifth ave": {
            "type": "property",
            "group": 3,
            "rent": [60, 220, 650, 1500, 1800, 2100, 3600],
            "mortgage": 215,
            "house": 300,
            "forward": ["madison ave"],
            "backward": ["pennsylvania railroad"],
            "side": [1],
            "track": [0],
            "below": ["st james pl"]
        },
        "madison ave": {
            "type": "property",
            "group": 3,
            "rent": [60, 220, 650, 1500, 1800, 2100, 3600],
            "mortgage": 215,
            "house": 300,
            "forward": ["stock exchange"],
            "backward": ["fifth ave"],
            "side": [1],
            "track": [0],
            "below": ["misfortune middle east"]
        },
        "wall st": {
            "type": "property",
            "group": 3,
            "rent": [80, 300, 800, 1800, 2200, 2700, 4200],
            "mortgage": 250,
            "house": 300,
            "forward": ["tax refund"],
            "backward": ["stock exchange"],
            "side": [2],
            "track": [0],
            "below": ["indiana ave"]
        },
        "lake st": {
            "type": "property",
            "group": 4,
            "rent": [1, 5, 15, 45, 80, 125, 625],
            "mortgage": 15,
            "house": 50,
            "forward": ["misfortune outer se"],
            "backward": ["subway"],
            "side": [0],
            "track": [2],
            "above": ["go"]
        },
        "nicollet ave": {
            "type": "property",
            "group": 4,
            "rent": [1, 5, 15, 45, 80, 125, 625],
            "mortgage": 15,
            "house": 50,
            "forward": ["hennepin ave"],
            "backward": ["misfortune outer se"],
            "side": [0],
            "track": [2],
            "above": ["mediterranean ave"]
        },
        "hennepin ave": {
            "type": "property",
            "group": 4,
            "rent": [3, 15, 45, 130, 240, 350, 850],
            "mortgage": 30,
            "house": 50,
            "forward": ["bus ticket south"],
            "backward": ["nicollet ave"],
            "side": [0],
            "track": [2],
            "above": ["misfortune middle south"]
        },
        "esplanade ave": {
            "type": "property",
            "group": 5,
            "rent": [5, 25, 80, 225, 360, 600, 1000],
            "mortgage": 50,
            "house": 50,
            "forward": ["canal st"],
            "backward": ["reading railroad"],
            "side": [0],
            "track": [2],
            "above": ["oriental ave"]
        },
        "katy freeway": {
            "type": "property",
            "group": 6,
            "rent": [11, 55, 160, 475, 650, 800, 1300],
            "mortgage": 70,
            "house": 100,
            "forward": ["westheimer rd"],
            "backward": ["auction"],
            "side": [1],
            "track": [2],
            "above": ["jail"]
        },
        "westheimer rd": {
            "type": "property",
            "group": 6,
            "rent": [11, 55, 160, 475, 650, 800, 1300],
            "mortgage": 70,
            "house": 100,
            "forward": ["internet service provider"],
            "backward": ["katy freeway"],
            "side": [1],
            "track": [2],
            "above": ["st charles pl"]
        },
        "kirby dr": {
            "type": "property",
            "group": 6,
            "rent": [14, 70, 200, 550, 750, 950, 1450],
            "mortgage": 80,
            "house": 100,
            "forward": ["cullen blvd"],
            "backward": ["internet service provider"],
            "side": [1],
            "track": [2],
            "above": ["states ave"]
        },
        "cullen blvd": {
            "type": "property",
            "group": 6,
            "rent": [14, 70, 200, 550, 750, 950, 1450],
            "mortgage": 80,
            "house": 100,
            "forward": ["fortune outer west"],
            "backward": ["kirby dr"],
            "side": [1],
            "track": [2],
            "above": ["virginia ave"]
        },
        "canal st": {
            "type": "property",
            "group": 5,
            "rent": [5, 25, 80, 225, 360, 600, 1000],
            "mortgage": 50,
            "house": 50,
            "forward": ["fortune outer south"],
            "backward": ["esplanade ave"],
            "side": [0],
            "track": [2],
            "above": ["fortune middle south"]
        },
        "magazine st": {
            "type": "property",
            "group": 5,
            "rent": [8, 40, 100, 300, 450, 600, 1100],
            "mortgage": 60,
            "house": 50,
            "forward": ["bourbon st"],
            "backward": ["cable company"],
            "side": [0],
            "track": [2],
            "above": ["jail"]
        },
        "bourbon st": {
            "type": "property",
            "group": 5,
            "rent": [8, 40, 100, 300, 450, 600, 1100],
            "mortgage": 60,
            "house": 50,
            "forward": ["holland tunnel sw"],
            "backward": ["magazine st"],
            "side": [0],
            "track": [2],
            "above": ["jail"]
        },
        "dekalb ave": {
            "type": "property",
            "group": 7,
            "rent": [17, 85, 240, 670, 840, 1025, 1525],
            "mortgage": 90,
            "house": 100,
            "forward": ["misfortune outer nw"],
            "backward": ["black & white cab co"],
            "side": [1],
            "track": [2],
            "above": ["misfortune middle west"]
        },
        "young int'l blvd": {
            "type": "property",
            "group": 7,
            "rent": [17, 85, 240, 670, 840, 1025, 1525],
            "mortgage": 90,
            "house": 100,
            "forward": ["decatur st"],
            "backward": ["misfortune outer nw"],
            "side": [1],
            "track": [2],
            "above": ["new york ave"]
        },
        "decatur st": {
            "type": "property",
            "group": 7,
            "rent": [20, 100, 300, 750, 925, 1100, 1600],
            "mortgage": 100,
            "house": 100,
            "forward": ["peachtree st"],
            "backward": ["young int'l blvd"],
            "side": [1],
            "track": [2],
            "above": ["free parking"]
        },
        "peachtree st": {
            "type": "property",
            "group": 7,
            "rent": [20, 100, 300, 750, 925, 1100, 1600],
            "mortgage": 100,
            "house": 100,
            "forward": ["pay day"],
            "backward": ["decatur st"],
            "side": [1],
            "track": [2],
            "above": ["free parking"]
        },
        "randolph st": {
            "type": "property",
            "group": 8,
            "rent": [23, 115, 345, 825, 1010, 1180, 2180],
            "mortgage": 110,
            "house": 150,
            "forward": ["fortune outer nw"],
            "backward": ["pay day"],
            "side": [2],
            "track": [2],
            "above": ["free parking"]
        },
        "lake shore dr": {
            "type": "property",
            "group": 8,
            "rent": [23, 115, 345, 825, 1010, 1180, 2180],
            "mortgage": 110,
            "house": 150,
            "forward": ["wacker dr"],
            "backward": ["fortune outer nw"],
            "side": [2],
            "track": [2],
            "above": ["kentucky ave"]
        },
        "wacker dr": {
            "type": "property",
            "group": 8,
            "rent": [26, 130, 390, 900, 1100, 1275, 2275],
            "mortgage": 120,
            "house": 150,
            "forward": ["michigan ave"],
            "backward": ["wacker dr"],
            "side": [2],
            "track": [2],
            "above": ["fortune middle north"]
        },
        "michigan ave": {
            "type": "property",
            "group": 8,
            "rent": [26, 130, 390, 900, 1100, 1275, 2275],
            "mortgage": 120,
            "house": 150,
            "forward": ["yellow cab co"],
            "backward": ["wacker dr"],
            "side": [2],
            "track": [2],
            "above": ["indiana ave"]
        },
        "south temple": {
            "type": "property",
            "group": 9,
            "rent": [32, 160, 470, 1050, 1250, 1500, 2500],
            "mortgage": 130,
            "house": 200,
            "forward": ["west temple"],
            "backward": ["misfortune outer north"],
            "side": [2],
            "track": [2],
            "above": ["ventnor ave"]
        },
        "west temple": {
            "type": "property",
            "group": 9,
            "rent": [32, 160, 470, 1050, 1250, 1500, 2500],
            "mortgage": 130,
            "house": 200,
            "forward": ["trash collector"],
            "backward": ["south temple"],
            "side": [2],
            "track": [2],
            "above": ["water works"]
        },
        "north temple": {
            "type": "property",
            "group": 9,
            "rent": [38, 170, 520, 1125, 1275, 1425, 1650],
            "mortgage": 140,
            "house": 200,
            "forward": ["temple square"],
            "backward": ["trash collector"],
            "side": [2],
            "track": [2],
            "above": ["roll3"]
        },
        "temple square": {
            "type": "property",
            "group": 9,
            "rent": [38, 170, 520, 1125, 1275, 1425, 1650],
            "mortgage": 140,
            "house": 200,
            "forward": ["go to jail"],
            "backward": ["north temple"],
            "side": [2],
            "track": [2],
            "above": ["roll3"]
        },
        "south st": {
            "type": "property",
            "group": 10,
            "rent": [45, 210, 575, 1300, 1600, 1800, 3300],
            "mortgage": 150,
            "house": 250,
            "forward": ["broad st"],
            "backward": ["go to jail"],
            "side": [3],
            "track": [2],
            "above": ["roll3"]
        },
        "broad st": {
            "type": "property",
            "group": 10,
            "rent": [45, 210, 575, 1300, 1600, 1800, 3300],
            "mortgage": 150,
            "house": 250,
            "forward": ["walnut st"],
            "backward": ["south st"],
            "side": [3],
            "track": [2],
            "above": ["roll3"]
        },
        "walnut st": {
            "type": "property",
            "group": 10,
            "rent": [55, 225, 630, 1450, 1750, 2050, 3350],
            "mortgage": 160,
            "house": 250,
            "forward": ["misfortune outer east"],
            "backward": ["broad st"],
            "side": [3],
            "track": [2],
            "above": ["pacific ave"]
        },
        "market st": {
            "type": "property",
            "group": 10,
            "rent": [55, 225, 630, 1450, 1750, 2050, 3350],
            "mortgage": 160,
            "house": 250,
            "forward": ["bus ticket east"],
            "backward": ["misfortune outer east"],
            "side": [3],
            "track": [2],
            "above": ["misfortune middle east"]
        },
        "mulholland dr": {
            "type": "property",
            "group": 11,
            "rent": [70, 350, 750, 1600, 1850, 2100, 3600],
            "mortgage": 175,
            "house": 300,
            "forward": ["ventura blvd"],
            "backward": ["birthday gift"],
            "side": [3],
            "track": [2],
            "above": ["luxury tax"]
        },
        "ventura blvd": {
            "type": "property",
            "group": 11,
            "rent": [80, 400, 825, 1800, 2175, 2550, 4050],
            "mortgage": 200,
            "house": 300,
            "forward": ["fortune outer se"],
            "backward": ["mulholland dr"],
            "side": [3],
            "track": [2],
            "above": ["boardwalk"]
        },
        "rodeo dr": {
            "type": "property",
            "group": 11,
            "rent": [90, 450, 900, 2000, 2500, 3000, 4500],
            "mortgage": 250,
            "house": 300,
            "forward": ["subway"],
            "backward": ["fortune outer se"],
            "side": [3],
            "track": [2],
            "above": ["go"]
        },
        "mediterranean ave": {
            "type": "property",
            "group": 12,
            "rent": [2, 10, 30, 90, 160, 250, 400],
            "mortgage": 30,
            "house": 50,
            "forward": ["misfortune middle south"],
            "backward": ["go"],
            "side": [0],
            "track": [1],
            "above": ["squeeze play"],
            "below": ["nicollet ave"]
        },
        "baltic ave": {
            "type": "property",
            "group": 12,
            "rent": [4, 20, 60, 180, 320, 450, 750],
            "mortgage": 30,
            "house": 50,
            "forward": ["income tax"],
            "backward": ["misfortune middle south"],
            "side": [0],
            "track": [1],
            "above": ["the embarcadero"],
            "below": ["bus ticket south"]
        },
        "oriental ave": {
            "type": "property",
            "group": 13,
            "rent": [6, 30, 90, 270, 400, 550, 900],
            "mortgage": 50,
            "house": 50,
            "forward": ["fortune middle south"],
            "backward": ["reading railroad"],
            "side": [0],
            "track": [1],
            "above": ["misfortune inner sw"],
            "below": ["esplanade ave"]
        },
        "vermont ave": {
            "type": "property",
            "group": 13,
            "rent": [6, 30, 90, 270, 400, 550, 900],
            "mortgage": 50,
            "house": 50,
            "forward": ["connecticut ave"],
            "backward": ["fortune middle south"],
            "side": [0],
            "track": [1],
            "above": ["bonus"],
            "below": ["fortune outer sw"]
        },
        "connecticut ave": {
            "type": "property",
            "group": 13,
            "rent": [8, 40, 100, 300, 450, 600, 1000],
            "mortgage": 60,
            "house": 50,
            "forward": ["jail"],
            "backward": ["vermont ave"],
            "side": [0],
            "track": [1],
            "above": ["bonus"],
            "below": ["cable company"]
        },
        "st charles pl": {
            "type": "property",
            "group": 14,
            "rent": [10, 50, 150, 450, 625, 750, 1200],
            "mortgage": 70,
            "house": 100,
            "forward": ["electric company"],
            "backward": ["jail"],
            "side": [1],
            "track": [1],
            "above": ["bonus"],
            "below": ["westheimer rd"]
        },
        "states ave": {
            "type": "property",
            "group": 14,
            "rent": [10, 50, 150, 450, 625, 750, 1200],
            "mortgage": 70,
            "house": 100,
            "forward": ["virginia ave"],
            "backward": ["electric company"],
            "side": [1],
            "track": [1],
            "above": ["boylston st"],
            "below": ["kirby dr"]
        },
        "virginia ave": {
            "type": "property",
            "group": 14,
            "rent": [12, 60, 180, 500, 700, 900, 1450],
            "mortgage": 80,
            "house": 100,
            "forward": ["pennsylvania railroad"],
            "backward": ["states ave"],
            "side": [1],
            "track": [1],
            "above": ["newbury st"],
            "below": ["cullen blvd"]
        },
        "st james pl": {
            "type": "property",
            "group": 15,
            "rent": [14, 70, 200, 550, 750, 950, 1500],
            "mortgage": 90,
            "house": 100,
            "forward": ["misfortune middle west"],
            "backward": ["pennsylvania railroad"],
            "side": [1],
            "track": [1],
            "above": ["fifth ave"],
            "below": ["black & white cab co"]
        },
        "tennessee ave": {
            "type": "property",
            "group": 15,
            "rent": [14, 70, 200, 550, 750, 950, 1500],
            "mortgage": 90,
            "house": 100,
            "forward": ["new york ave"],
            "backward": ["misfortune middle west"],
            "side": [1],
            "track": [1],
            "above": ["stock exchange"],
            "below": ["misfortune outer nw"]
        },
        "new york ave": {
            "type": "property",
            "group": 15,
            "rent": [16, 80, 220, 600, 800, 1000, 1600],
            "mortgage": 100,
            "house": 100,
            "forward": ["free parking"],
            "backward": ["tennessee ave"],
            "side": [1],
            "track": [1],
            "above": ["stock exchange"],
            "below": ["young int'l blvd"]
        },
        "kentucky ave": {
            "type": "property",
            "group": 16,
            "rent": [18, 90, 250, 700, 875, 1050, 1700],
            "mortgage": 110,
            "house": 150,
            "forward": ["fortune middle north"],
            "backward": ["free parking"],
            "side": [2],
            "track": [1],
            "above": ["stock exchange"],
            "below": ["lake shore dr"]
        },
        "indiana ave": {
            "type": "property",
            "group": 16,
            "rent": [18, 90, 250, 700, 875, 1050, 1700],
            "mortgage": 110,
            "house": 150,
            "forward": ["illinois ave"],
            "backward": ["fortune middle north"],
            "side": [2],
            "track": [1],
            "above": ["wall st"],
            "below": ["michigan ave"]
        },
        "illinois ave": {
            "type": "property",
            "group": 16,
            "rent": [20, 100, 300, 750, 925, 1100, 1750],
            "mortgage": 120,
            "house": 150,
            "forward": ["b&o railroad"],
            "backward": ["indiana ave"],
            "side": [2],
            "track": [1],
            "above": ["tax refund"],
            "below": ["yellow cab co"]
        },
        "atlantic ave": {
            "type": "property",
            "group": 17,
            "rent": [22, 110, 330, 800, 975, 1150, 1850],
            "mortgage": 130,
            "house": 150,
            "forward": ["ventnor ave"],
            "backward": ["b&o railroad"],
            "side": [2],
            "track": [1],
            "above": ["fortune inner ne"],
            "below": ["misfortune outer north"]
        },
        "ventnor ave": {
            "type": "property",
            "group": 17,
            "rent": [22, 110, 330, 800, 975, 1150, 1850],
            "mortgage": 130,
            "house": 150,
            "forward": ["water works"],
            "backward": ["atlantic ave"],
            "side": [2],
            "track": [1],
            "above": ["florida ave"],
            "below": ["south temple"]
        },
        "marvin gardens": {
            "type": "property",
            "group": 17,
            "rent": [24, 120, 360, 850, 1025, 1200, 1900],
            "mortgage": 140,
            "house": 150,
            "forward": ["roll3"],
            "backward": ["water works"],
            "side": [2],
            "track": [1],
            "above": ["holland tunnel ne"],
            "below": ["trash collector"]
        },
        "pacific ave": {
            "type": "property",
            "group": 18,
            "rent": [26, 120, 390, 900, 1100, 1275, 2050],
            "mortgage": 150,
            "house": 200,
            "forward": ["north carolina ave"],
            "backward": ["roll3"],
            "side": [3],
            "track": [1],
            "above": ["holland tunnel ne"],
            "below": ["walnut st"]
        },
        "north carolina ave": {
            "type": "property",
            "group": 18,
            "rent": [26, 120, 390, 900, 1100, 1275, 2050],
            "mortgage": 150,
            "house": 200,
            "forward": ["misfortune middle east"],
            "backward": ["pacific ave"],
            "side": [3],
            "track": [1],
            "above": ["holland tunnel ne"],
            "below": ["misfortune outer east"]
        },
        "pennsylvania ave": {
            "type": "property",
            "group": 18,
            "rent": [28, 150, 450, 1000, 1200, 1400, 2200],
            "mortgage": 160,
            "house": 200,
            "forward": ["short line"],
            "backward": ["misfortune middle east"],
            "side": [3],
            "track": [1],
            "above": ["biscayne ave"],
            "below": ["bus ticket east"]
        },
        "park pl": {
            "type": "property",
            "group": 19,
            "rent": [35, 175, 500, 1100, 1300, 1500, 2400],
            "mortgage": 175,
            "house": 200,
            "forward": ["luxury tax"],
            "backward": ["fortune middle east"],
            "side": [3],
            "track": [1],
            "above": ["lombard st"],
            "below": ["birthday gift"]
        },
        "boardwalk": {
            "type": "property",
            "group": 19,
            "rent": [50, 200, 600, 1400, 1700, 2000, 3200],
            "mortgage": 200,
            "house": 200,
            "forward": ["go"],
            "backward": ["luxury tax"],
            "side": [3],
            "track": [1],
            "above": ["squeeze play"],
            "below": ["ventura blvd"]
        },
        "checker cab co": {
            "type": "cab",
            "group": 20,
            "rent": [30, 60, 120, 240],
            "mortgage": 150,
            "forward": ["reading railroad"],
            "backward": ["bus ticket south"],
            "side": [0],
            "track": [2],
            "above": ["income tax"]
        },
        "black & white cab co": {
            "type": "cab",
            "group": 20,
            "rent": [30, 60, 120, 240],
            "mortgage": 150,
            "forward": ["dekalb ave"],
            "backward": ["fortune outer west"],
            "side": [1],
            "track": [2],
            "above": ["st james pl"]
        },
        "yellow cab co": {
            "type": "cab",
            "group": 20,
            "rent": [30, 60, 120, 240],
            "mortgage": 150,
            "forward": ["b&o railroad"],
            "backward": ["michigan ave"],
            "side": [2],
            "track": [2],
            "above": ["illinois ave"]
        },
        "ute cab co": {
            "type": "cab",
            "group": 20,
            "rent": [30, 60, 120, 240],
            "mortgage": 150,
            "forward": ["birthday gift"],
            "backward": ["sewage system"],
            "side": [3],
            "track": [1],
            "above": ["fortune middle east"]
        },
        "water works": {
            "type": "utility",
            "group": 21,
            "rent": [4, 10, 20, 40, 80, 100, 120, 150],
            "mortgage": 75,
            "forward": ["marvin gardens"],
            "backward": ["ventnor ave"],
            "side": [2],
            "track": [1],
            "above": ["holland tunnel ne"],
            "below": ["west temple"]
        },
        "cable company": {
            "type": "utility",
            "group": 21,
            "rent": [4, 10, 20, 40, 80, 100, 120, 150],
            "mortgage": 75,
            "forward": ["magazine st"],
            "backward": ["fortune outer south"],
            "side": [0],
            "track": [2],
            "above": ["connecticut ave"]
        },
        "electric company": {
            "type": "utility",
            "group": 21,
            "rent": [4, 10, 20, 40, 80, 100, 120, 150],
            "mortgage": 75,
            "forward": ["states ave"],
            "backward": ["st charles pl"],
            "side": [1],
            "track": [1],
            "above": ["bonus"],
            "below": ["internet service provider"]
        },
        "internet service provider": {
            "type": "utility",
            "group": 21,
            "rent": [4, 10, 20, 40, 80, 100, 120, 150],
            "mortgage": 75,
            "forward": ["kirby dr"],
            "backward": ["westheimer rd"],
            "side": [1],
            "track": [2],
            "above": ["electric company"]
        },
        "gas company": {
            "type": "utility",
            "group": 21,
            "rent": [4, 10, 20, 40, 80, 100, 120, 150],
            "mortgage": 75,
            "forward": ["fortune inner ne"],
            "backward": ["tax refund"],
            "side": [2],
            "track": [0],
            "below": ["b&o railroad"]
        },
        "telephone company": {
            "type": "utility",
            "group": 21,
            "rent": [4, 10, 20, 40, 80, 100, 120, 150],
            "mortgage": 75,
            "forward": ["misfortune inner sw"],
            "backward": ["fisherman's wharf"],
            "side": [0],
            "track": [0],
            "below": ["reading railroad"]
        },
        "trash collector": {
            "type": "utility",
            "group": 21,
            "rent": [4, 10, 20, 40, 80, 100, 120, 150],
            "mortgage": 75,
            "forward": ["north temple"],
            "backward": ["west temple"],
            "side": [2],
            "track": [2],
            "above": ["marvin gardens"]
        },
        "sewage system": {
            "type": "utility",
            "group": 21,
            "rent": [4, 10, 20, 40, 80, 100, 120, 150],
            "mortgage": 75,
            "forward": ["ute cab co"],
            "backward": ["bus ticket east"],
            "side": [3],
            "track": [2],
            "above": ["short line"]
        },
        "reading railroad": {
            "type": "railroad",
            "group": 22,
            "rent": [25, 50, 100, 200],
            "mortgage": 100,
            "forward": ["oriental ave", "esplanade ave"],
            "backward": ["income tax", "checker cab co"],
            "side": [0],
            "track": [1, 2],
            "above": ["telephone company"]
        },
        "pennsylvania railroad": {
            "type": "railroad",
            "group": 22,
            "rent": [25, 50, 100, 200],
            "mortgage": 100,
            "forward": ["fifth ave", "st james pl"],
            "backward": ["newbury st", "virginia ave"],
            "side": [1],
            "track": [0, 1],
            "below": ["fortune outer west"]
        },
        "b&o railroad": {
            "type": "railroad",
            "group": 22,
            "rent": [25, 50, 100, 200],
            "mortgage": 100,
            "forward": ["atlantic ave", "misfortune outer north"],
            "backward": ["illinois ave", "yellow cab co"],
            "side": [2],
            "track": [1, 2],
            "above": ["gas company"]
        },
        "short line": {
            "type": "railroad",
            "group": 22,
            "rent": [25, 50, 100, 200],
            "mortgage": 100,
            "forward": ["reverse", "fortune middle east"],
            "backward": ["biscayne ave", "pennsylvania ave"],
            "side": [3],
            "track": [0, 1],
            "below": ["sewage system"]
        },
        "holland tunnel ne": {
            "type": "teleport",
            "forward": ["miami ave"],
            "backward": ["florida ave"],
            "teleport": ["holland tunnel sw", [2]],
            "side": [2, 3],
            "track": [0],
            "below": ["roll3"]
        },
        "holland tunnel sw": {
            "type": "teleport",
            "forward": ["auction"],
            "backward": ["bourbon st"],
            "teleport": ["holland tunnel ne", [0]],
            "side": [0, 1],
            "track": [2],
            "above": ["jail"]
        },
        "fortune inner ne": {
            "type": "fortune",
            "forward": ["florida ave"],
            "backward": ["gas company"],
            "side": [2],
            "track": [0],
            "below": ["atlantic ave"]
        },
        "fortune outer west": {
            "type": "fortune",
            "forward": ["black & white cab co"],
            "backward": ["cullen blvd"],
            "side": [1],
            "track": [2],
            "above": ["pennsylvania railroad"]
        },
        "fortune outer nw": {
            "type": "fortune",
            "forward": ["lake shore dr"],
            "backward": ["randolph st"],
            "side": [2],
            "track": [2],
            "above": ["free parking"]
        },
        "fortune outer south": {
            "type": "fortune",
            "forward": ["cable company"],
            "backward": ["canal st"],
            "side": [0],
            "track": [2],
            "above": ["vermont ave"]
        },
        "fortune outer se": {
            "type": "fortune",
            "forward": ["rodeo dr"],
            "backward": ["ventura blvd"],
            "side": [3],
            "track": [2],
            "above": ["go"]
        },
        "fortune middle east": {
            "type": "fortune",
            "forward": ["park pl"],
            "backward": ["short line"],
            "side": [3],
            "track": [1],
            "above": ["reverse"],
            "below": ["ute cab co"]
        },
        "fortune middle south": {
            "type": "fortune",
            "forward": ["vermont ave"],
            "backward": ["oriental ave"],
            "side": [0],
            "track": [1],
            "above": ["beacon st"],
            "below": ["canal st"]
        },
        "fortune middle north": {
            "type": "fortune",
            "forward": ["indiana ave"],
            "backward": ["kentucky ave"],
            "side": [2],
            "track": [1],
            "above": ["stock exchange"],
            "below": ["wacker dr"]
        },
        "squeeze play": {
            "type": "squeeze play",
            "forward": ["the embarcadero"],
            "backward": ["lombard st"],
            "side": [3, 0],
            "track": [0],
            "below": ["go"]
        },
        "reverse": {
            "type": "reverse",
            "forward": ["lombard st"],
            "backward": ["short line"],
            "side": [3],
            "track": [0],
            "below": ["fortune middle east"]
        },
        "bonus": {
            "type": "collect",
            "forward": ["boylston st"],
            "backward": ["beacon st"],
            "amount": [300, 250],
            "gain": "land/pass",
            "side": [0, 1],
            "track": [0],
            "below": ["jail"]
        },
        "pay day": {
            "type": "collect",
            "forward": ["randolph st"],
            "backward": ["peachtree st"],
            "amount": [300, 400],
            "gain": "odd/even",
            "side": [1, 2],
            "track": [2],
            "above": ["free parking"]
        },
        "misfortune inner sw": {
            "type": "misfortune",
            "forward": ["beacon st"],
            "backward": ["telephone company"],
            "side": [0],
            "track": [0],
            "below": ["oriental ave"]
        },
        "misfortune outer se": {
            "type": "misfortune",
            "forward": ["nicollet ave"],
            "backward": ["lake st"],
            "side": [0],
            "track": [2],
            "above": ["go"]
        },
        "misfortune outer nw": {
            "type": "misfortune",
            "forward": ["young int'l blvd"],
            "backward": ["dekalb ave"],
            "side": [1],
            "track": [2],
            "above": ["tennessee ave"]
        },
        "misfortune outer north": {
            "type": "misfortune",
            "forward": ["south temple"],
            "backward": ["b&o railroad"],
            "side": [2],
            "track": [2],
            "above": ["atlantic ave"],
        },
        "misfortune outer east": {
            "type": "misfortune",
            "forward": ["market st"],
            "backward": ["walnut st"],
            "side": [3],
            "track": [2],
            "above": ["north carolina ave"]
        },
        "misfortune middle south": {
            "type": "misfortune",
            "forward": ["baltic ave"],
            "backward": ["mediterranean ave"],
            "side": [0],
            "track": [1],
            "above": ["squeeze play"],
            "below": ["hennepin ave"]
        },
        "misfortune middle west": {
            "type": "misfortune",
            "forward": ["tennessee ave"],
            "backward": ["st james pl"],
            "side": [1],
            "track": [1],
            "above": ["madison ave"],
            "below": ["dekalb ave"]
        },
        "misfortune middle east": {
            "type": "misfortune",
            "forward": ["pennsylvania ave"],
            "backward": ["north carolina ave"],
            "side": [3],
            "track": [1],
            "above": ["miami ave"],
            "below": ["market st"]
        },
        "stock exchange": {
            "type": "stock",
            "forward": ["wall st"],
            "backward": ["madison ave"],
            "side": [1, 2],
            "track": [0],
            "below": ["free parking"]
        },
        "tax refund": {
            "type": "place",
            "forward": ["gas company"],
            "backward": ["wall st"],
            "side": [2],
            "track": [0],
            "below": ["illinois ave"]
        },
        "subway": {
            "type": "subway",
            "forward": ["lake st"],
            "backward": ["rodeo dr"],
            "side": [3, 0],
            "track": [2],
            "above": ["go"]
        },
        "bus ticket south": {
            "type": "bus",
            "forward": ["checker cab co"],
            "backward": ["hennepin ave"],
            "side": [0],
            "track": [2],
            "above": ["baltic ave"]
        },
        "bus ticket east": {
            "type": "bus",
            "forward": ["sewage system"],
            "backward": ["ute cab co"],
            "side": [3],
            "track": [2],
            "above": ["pennsylvania ave"]
        },
        "auction": {
            "type": "auction",
            "forward": ["katy freeway"],
            "backward": ["holland tunnel sw"],
            "side": [1],
            "track": [2],
            "above": ["jail"]
        },
        "go to jail": {
            "type": "teleport",
            "forward": ["south st"],
            "backward": ["temple square"],
            "teleport": ["jail", [1]],
            "side": [2, 3],
            "track": [2],
            "above": ["roll3"]
        },
        "jail": {
            "type": "place",
            "forward": ["st charles pl"],
            "backward": ["connecticut ave"],
            "side": [0, 1],
            "track": [1],
            "above": ["bonus"],
            "below": ["holland tunnel sw"]
        },
        "birthday gift": {
            "type": "place",
            "forward": ["mulholland dr"],
            "backward": ["ute cab co"],
            "side": [3],
            "track": [2],
            "above": ["park pl"],
        },
        "income tax": {
            "type": "place",
            "forward": ["reading railroad"],
            "backward": ["baltic ave"],
            "side": [0],
            "track": [1],
            "above": ["fisherman's wharf"],
            "below": ["checker cab co"]
        },
        "go": {
            "type": "collect",
            "forward": ["mediterranean ave"],
            "backward": ["boardwalk"],
            "amount": [200, 200],
            "gain": "land/pass",
            "side": [3, 0],
            "track": [1],
            "above": ["squeeze play"],
            "below": ["subway"]
        },
        "free parking": {
            "type": "place",
            "forward": ["kentucky ave"],
            "backward": ["new york ave"],
            "side": [1, 2],
            "track": [1],
            "above": ["stock exchange"],
            "below": ["pay day"]
        },
        "roll3": {
            "type": "place",
            "forward": ["pacific ave"],
            "backward": ["marvin gardens"],
            "side": [2, 3],
            "track": [1],
            "above": ["holland tunnel ne"],
            "below": ["go to jail"]
        },
        "luxury tax": {
            "type": "place",
            "forward": ["boardwalk"],
            "backward": ["park pl"],
            "side": [3],
            "track": [1],
            "above": ["squeeze play"],
            "below": ["mulholland dr"]
        }
    }
}