module.exports = {
	"biscayne ave": {
		"type": "property",
		"quality": "fake red",
		"rent": [11, 55, 160, 475, 650, 800, 1300],
		"mortgage": 75,
		"house": 50,
		"forward": ["short line"],
		"backward": ["miami ave"],
		"side": "right",
		"track": ["inner"],
		"below": ["pennsylvania ave"]
	},
	"miami ave": {
		"type": "property",
		"quality": "fake red",
		"rent": [9, 45, 120, 350, 500, 700, 1200],
		"mortgage": 65,
		"house": 50,
		"forward": ["biscayne ave"],
		"backward": ["holland tunnel ne"],
		"side": "right",
		"track": ["inner"],
		"below": ["community chest middle east"]
	},
	"florida ave": {
		"type": "property",
		"quality": "fake red",
		"rent": [9, 45, 120, 350, 500, 700, 1200],
		"mortgage": 65,
		"house": 50,
		"forward": ["holland tunnel ne"],
		"backward": ["chance inner ne"],
		"side": "top",
		"track": ["inner"],
		"below": ["ventnor ave"]
	},
	"lombard st": {
		"type": "property",
		"quality": "white",
		"rent": [17, 85, 240, 475, 670, 1025, 1525],
		"mortgage": 105,
		"house": 100,
		"forward": ["squeeze play"],
		"backward": ["reverse"],
		"side": "right",
		"track": ["inner"],
		"below": ["park pl"]
	},
	"the embarcadero": {
		"type": "property",
		"quality": "white",
		"rent": [17, 85, 240, 475, 670, 1025, 1525],
		"mortgage": 105,
		"house": 100,
		"forward": ["fisherman's wharf"],
		"backward": ["squeeze play"],
		"side": "bottom",
		"track": ["inner"],
		"below": ["baltic ave"]
	},
	"fisherman's wharf": {
		"type": "property",
		"quality": "white",
		"rent": [21, 105, 320, 780, 950, 1125, 1625],
		"mortgage": 125,
		"house": 100,
		"forward": ["telephone company"],
		"backward": ["the embarcadero"],
		"side": "bottom",
		"track": ["inner"],
		"below": ["income tax"]
	},
	"beacon st": {
		"type": "property",
		"quality": "black",
		"rent": [30, 160, 470, 1050, 1250, 1500, 2500],
		"mortgage": 165,
		"house": 200,
		"forward": ["bonus"],
		"backward": ["community chest inner sw"],
		"side": "bottom",
		"track": ["inner"],
		"below": ["chance middle south"]
	},
	"boylston st": {
		"type": "property",
		"quality": "black",
		"rent": [30, 160, 470, 1050, 1250, 1500, 2500],
		"mortgage": 165,
		"house": 200,
		"forward": ["newbury st"],
		"side": "left",
		"backward": ["bonus"],
		"track": ["inner"],
		"below": ["states ave"]
	},
	"newbury st": {
		"type": "property",
		"quality": "black",
		"rent": [40, 185, 550, 1200, 1500, 1700, 2700],
		"mortgage": 190,
		"house": 200,
		"forward": ["pennsylvania railroad"],
		"backward": ["boylston st"],
		"side": "left",
		"track": ["inner"],
		"below": ["virginia ave"]
	},
	"fifth ave": {
		"type": "property",
		"quality": "gray",
		"rent": [60, 220, 650, 1500, 1800, 2100, 3600],
		"mortgage": 215,
		"house": 300,
		"forward": ["madison ave"],
		"backward": ["pennsylvania railroad"],
		"side": "left",
		"track": ["inner"],
		"below": ["st james pl"]
	},
	"madison ave": {
		"type": "property",
		"quality": "gray",
		"rent": [60, 220, 650, 1500, 1800, 2100, 3600],
		"mortgage": 215,
		"house": 300,
		"forward": ["stock exchange"],
		"backward": ["fifth ave"],
		"side": "left",
		"track": ["inner"],
		"below": ["community chest middle east"]
	},
	"wall st": {
		"type": "property",
		"quality": "gray",
		"rent": [80, 300, 800, 1800, 2200, 2700, 4200],
		"mortgage": 250,
		"house": 300,
		"forward": ["tax refund"],
		"backward": ["stock exchange"],
		"side": "top",
		"track": ["inner"],
		"below": ["indiana ave"]
	},
	"lake st": {
		"type": "property",
		"quality": "light pink",
		"rent": [1, 5, 15, 45, 80, 125, 625],
		"mortgage": 15,
		"house": 50,
		"forward": ["community chest outer se"],
		"backward": ["subway"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["go"]
	},
	"nicollet ave": {
		"type": "property",
		"quality": "light pink",
		"rent": [1, 5, 15, 45, 80, 125, 625],
		"mortgage": 15,
		"house": 50,
		"forward": ["hennepin ave"],
		"backward": ["community chest outer se"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["mediterranean ave"]
	},
	"hennepin ave": {
		"type": "property",
		"quality": "light pink",
		"rent": [3, 15, 45, 130, 240, 350, 850],
		"mortgage": 30,
		"house": 50,
		"forward": ["bus ticket south"],
		"backward": ["nicollet ave"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["community chest middle south"]
	},
	"esplanade ave": {
		"type": "property",
		"quality": "light green",
		"rent": [5, 25, 80, 225, 360, 600, 1000],
		"mortgage": 50,
		"house": 50,
		"forward": ["canal st"],
		"backward": ["reading railroad"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["oriental ave"]
	},
	"katy freeway": {
		"type": "property",
		"quality": "light yellow",
		"rent": [11, 55, 160, 475, 650, 800, 1300],
		"mortgage": 70,
		"house": 100,
		"forward": ["westheimer rd"],
		"backward": ["auction"],
		"side": "left",
		"track": ["outer"],
		"above": ["jail"]
	},
	"westheimer rd": {
		"type": "property",
		"quality": "light yellow",
		"rent": [11, 55, 160, 475, 650, 800, 1300],
		"mortgage": 70,
		"house": 100,
		"forward": ["internet service provider"],
		"backward": ["katy freeway"],
		"side": "left",
		"track": ["outer"],
		"above": ["st charles pl"]
	},
	"kirby dr": {
		"type": "property",
		"quality": "light yellow",
		"rent": [14, 70, 200, 550, 750, 950, 1450],
		"mortgage": 80,
		"house": 100,
		"forward": ["cullen blvd"],
		"backward": ["internet service provider"],
		"side": "left",
		"track": ["outer"],
		"above": ["states ave"]
	},
	"cullen blvd": {
		"type": "property",
		"quality": "light yellow",
		"rent": [14, 70, 200, 550, 750, 950, 1450],
		"mortgage": 80,
		"house": 100,
		"forward": ["chance outer west"],
		"backward": ["kirby dr"],
		"side": "left",
		"track": ["outer"],
		"above": ["virginia ave"]
	},
	"canal st": {
		"type": "property",
		"quality": "light green",
		"rent": [5, 25, 80, 225, 360, 600, 1000],
		"mortgage": 50,
		"house": 50,
		"forward": ["chance outer south"],
		"backward": ["esplanade ave"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["chance middle south"]
	},
	"magazine st": {
		"type": "property",
		"quality": "light green",
		"rent": [8, 40, 100, 300, 450, 600, 1100],
		"mortgage": 60,
		"house": 50,
		"forward": ["bourbon st"],
		"backward": ["cable company"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["jail"]
	},
	"bourbon st": {
		"type": "property",
		"quality": "light green",
		"rent": [8, 40, 100, 300, 450, 600, 1100],
		"mortgage": 60,
		"house": 50,
		"forward": ["holland tunnel sw"],
		"backward": ["magazine st"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["jail"]
	},
	"dekalb ave": {
		"type": "property",
		"quality": "sea green",
		"rent": [17, 85, 240, 670, 840, 1025, 1525],
		"mortgage": 90,
		"house": 100,
		"forward": ["community chest outer nw"],
		"backward": ["black & white cab co"],
		"side": "left",
		"track": ["outer"],
		"above": ["community chest middle west"]
	},
	"young int'l blvd": {
		"type": "property",
		"quality": "sea green",
		"rent": [17, 85, 240, 670, 840, 1025, 1525],
		"mortgage": 90,
		"house": 100,
		"forward": ["decatur st"],
		"backward": ["community chest outer nw"],
		"side": "left",
		"track": ["outer"],
		"above": ["new york ave"]
	},
	"decatur st": {
		"type": "property",
		"quality": "sea green",
		"rent": [20, 100, 300, 750, 925, 1100, 1600],
		"mortgage": 100,
		"house": 100,
		"forward": ["peachtree st"],
		"backward": ["young int'l blvd"],
		"side": "left",
		"track": ["outer"],
		"above": ["free parking"]
	},
	"peachtree st": {
		"type": "property",
		"quality": "sea green",
		"rent": [20, 100, 300, 750, 925, 1100, 1600],
		"mortgage": 100,
		"house": 100,
		"forward": ["pay day"],
		"backward": ["decatur st"],
		"side": "left",
		"track": ["outer"],
		"above": ["free parking"]
	},
	"randolph st": {
		"type": "property",
		"quality": "dark maroon",
		"rent": [23, 115, 345, 825, 1010, 1180, 2180],
		"mortgage": 110,
		"house": 150,
		"forward": ["chance outer nw"],
		"backward": ["pay day"],
		"side": "top",
		"track": ["outer"],
		"above": ["free parking"]
	},
	"lake shore dr": {
		"type": "property",
		"quality": "dark maroon",
		"rent": [23, 115, 345, 825, 1010, 1180, 2180],
		"mortgage": 110,
		"house": 150,
		"forward": ["wacker dr"],
		"backward": ["chance outer nw"],
		"side": "top",
		"track": ["outer"],
		"above": ["kentucky ave"]
	},
	"wacker dr": {
		"type": "property",
		"quality": "dark maroon",
		"rent": [26, 130, 390, 900, 1100, 1275, 2275],
		"mortgage": 120,
		"house": 150,
		"forward": ["michigan ave"],
		"backward": ["wacker dr"],
		"side": "top",
		"track": ["outer"],
		"above": ["chance middle north"]
	},
	"michigan ave": {
		"type": "property",
		"quality": "dark maroon",
		"rent": [26, 130, 390, 900, 1100, 1275, 2275],
		"mortgage": 120,
		"house": 150,
		"forward": ["yellow cab co"],
		"backward": ["wacker dr"],
		"side": "top",
		"track": ["outer"],
		"above": ["indiana ave"]
	},
	"south temple": {
		"type": "property",
		"quality": "gold",
		"rent": [32, 160, 470, 1050, 1250, 1500, 2500],
		"mortgage": 130,
		"house": 200,
		"forward": ["west temple"],
		"backward": ["community chest outer north"],
		"side": "top",
		"track": ["outer"],
		"above": ["ventnor ave"]
	},
	"west temple": {
		"type": "property",
		"quality": "gold",
		"rent": [32, 160, 470, 1050, 1250, 1500, 2500],
		"mortgage": 130,
		"house": 200,
		"forward": ["trash collector"],
		"backward": ["south temple"],
		"side": "top",
		"track": ["outer"],
		"above": ["water works"]
	},
	"north temple": {
		"type": "property",
		"quality": "gold",
		"rent": [38, 170, 520, 1125, 1275, 1425, 1650],
		"mortgage": 140,
		"house": 200,
		"forward": ["temple square"],
		"backward": ["trash collector"],
		"side": "top",
		"track": ["outer"],
		"above": ["roll3"]
	},
	"temple square": {
		"type": "property",
		"quality": "gold",
		"rent": [38, 170, 520, 1125, 1275, 1425, 1650],
		"mortgage": 140,
		"house": 200,
		"forward": ["go to jail"],
		"backward": ["north temple"],
		"side": "top",
		"track": ["outer"],
		"above": ["roll3"]
	},
	"south st": {
		"type": "property",
		"quality": "light orange",
		"rent": [45, 210, 575, 1300, 1600, 1800, 3300],
		"mortgage": 150,
		"house": 250,
		"forward": ["broad st"],
		"backward": ["go to jail"],
		"side": "right",
		"track": ["outer"],
		"above": ["roll3"]
	},
	"broad st": {
		"type": "property",
		"quality": "light orange",
		"rent": [45, 210, 575, 1300, 1600, 1800, 3300],
		"mortgage": 150,
		"house": 250,
		"forward": ["walnut st"],
		"backward": ["south st"],
		"side": "right",
		"track": ["outer"],
		"above": ["roll3"]
	},
	"walnut st": {
		"type": "property",
		"quality": "light orange",
		"rent": [55, 225, 630, 1450, 1750, 2050, 3350],
		"mortgage": 160,
		"house": 250,
		"forward": ["community chest outer east"],
		"backward": ["broad st"],
		"side": "right",
		"track": ["outer"],
		"above": ["pacific ave"]
	},
	"market st": {
		"type": "property",
		"quality": "light orange",
		"rent": [55, 225, 630, 1450, 1750, 2050, 3350],
		"mortgage": 160,
		"house": 250,
		"forward": ["bus ticket east"],
		"backward": ["community chest outer east"],
		"side": "right",
		"track": ["outer"],
		"above": ["community chest middle east"]
	},
	"mulholland dr": {
		"type": "property",
		"quality": "maroon",
		"rent": [70, 350, 750, 1600, 1850, 2100, 3600],
		"mortgage": 175,
		"house": 300,
		"forward": ["ventura blvd"],
		"backward": ["birthday gift"],
		"side": "right",
		"track": ["outer"],
		"above": ["luxury tax"]
	},
	"ventura blvd": {
		"type": "property",
		"quality": "maroon",
		"rent": [80, 400, 825, 1800, 2175, 2550, 4050],
		"mortgage": 200,
		"house": 300,
		"forward": ["chance outer se"],
		"backward": ["mulholland dr"],
		"side": "right",
		"track": ["outer"],
		"above": ["boardwalk"]
	},
	"rodeo dr": {
		"type": "property",
		"quality": "maroon",
		"rent": [90, 450, 900, 2000, 2500, 3000, 4500],
		"mortgage": 250,
		"house": 300,
		"forward": ["subway"],
		"backward": ["chance outer se"],
		"side": "right",
		"track": ["outer"],
		"above": ["go"]
	},
	"mediterranean ave": {
		"type": "property",
		"quality": "brown",
		"rent": [2, 10, 30, 90, 160, 250, 400],
		"mortgage": 30,
		"house": 50,
		"forward": ["community chest middle south"],
		"backward": ["go"],
		"side": "bottom",
		"track": ["middle"],
		"above": ["squeeze play"],
		"below": ["nicollet ave"]
	},
	"baltic ave": {
		"type": "property",
		"quality": "brown",
		"rent": [4, 20, 60, 180, 320, 450, 750],
		"mortgage": 30,
		"house": 50,
		"forward": ["income tax"],
		"backward": ["community chest middle south"],
		"side": "bottom",
		"track": ["middle"],
		"above": ["the embarcadero"],
		"below": ["bus ticket south"]
	},
	"oriental ave": {
		"type": "property",
		"quality": "light blue",
		"rent": [6, 30, 90, 270, 400, 550, 900],
		"mortgage": 50,
		"house": 50,
		"forward": ["chance middle south"],
		"backward": ["reading railroad"],
		"side": "bottom",
		"track": ["middle"],
		"above": ["community chest inner sw"],
		"below": ["esplanade ave"]
	},
	"vermont ave": {
		"type": "property",
		"quality": "light blue",
		"rent": [6, 30, 90, 270, 400, 550, 900],
		"mortgage": 50,
		"house": 50,
		"forward": ["connecticut ave"],
		"backward": ["chance middle south"],
		"side": "bottom",
		"track": ["middle"],
		"above": ["bonus"],
		"below": ["chance outer sw"]
	},
	"connecticut ave": {
		"type": "property",
		"quality": "light blue",
		"rent": [8, 40, 100, 300, 450, 600, 1000],
		"mortgage": 60,
		"house": 50,
		"forward": ["in jail"],
		"backward": ["vermont ave"],
		"side": "bottom",
		"track": ["middle"],
		"above": ["bonus"],
		"below": ["cable company"]
	},
	"st charles pl": {
		"type": "property",
		"quality": "pink",
		"rent": [10, 50, 150, 450, 625, 750, 1200],
		"mortgage": 70,
		"house": 100,
		"forward": ["electric company"],
		"backward": ["in jail"],
		"side": "left",
		"track": ["middle"],
		"above": ["bonus"],
		"below": ["westheimer rd"]
	},
	"states ave": {
		"type": "property",
		"quality": "pink",
		"rent": [10, 50, 150, 450, 625, 750, 1200],
		"mortgage": 70,
		"house": 100,
		"forward": ["virginia ave"],
		"backward": ["electric company"],
		"side": "left",
		"track": ["middle"],
		"above": ["boylston st"],
		"below": ["kirby dr"]
	},
	"virginia ave": {
		"type": "property",
		"quality": "pink",
		"rent": [12, 60, 180, 500, 700, 900, 1450],
		"mortgage": 80,
		"house": 100,
		"forward": ["pennsylvania railroad"],
		"backward": ["states ave"],
		"side": "left",
		"track": ["middle"],
		"above": ["newbury st"],
		"below": ["cullen blvd"]
	},
	"st james pl": {
		"type": "property",
		"quality": "orange",
		"rent": [14, 70, 200, 550, 750, 950, 1500],
		"mortgage": 90,
		"house": 100,
		"forward": ["community chest middle west"],
		"backward": ["pennsylvania railroad"],
		"side": "left",
		"track": ["middle"],
		"above": ["fifth ave"],
		"below": ["black & white cab co"]
	},
	"tennessee ave": {
		"type": "property",
		"quality": "orange",
		"rent": [14, 70, 200, 550, 750, 950, 1500],
		"mortgage": 90,
		"house": 100,
		"forward": ["new york ave"],
		"backward": ["community chest middle west"],
		"side": "left",
		"track": ["middle"],
		"above": ["stock exchange"],
		"below": ["community chest outer nw"]
	},
	"new york ave": {
		"type": "property",
		"quality": "orange",
		"rent": [16, 80, 220, 600, 800, 1000, 1600],
		"mortgage": 100,
		"house": 100,
		"forward": ["free parking"],
		"backward": ["tennessee ave"],
		"side": "left",
		"track": ["middle"],
		"above": ["stock exchange"],
		"below": ["young int'l blvd"]
	},
	"kentucky ave": {
		"type": "property",
		"quality": "red",
		"rent": [18, 90, 250, 700, 875, 1050, 1700],
		"mortgage": 110,
		"house": 150,
		"forward": ["chance middle north"],
		"backward": ["free parking"],
		"side": "top",
		"track": ["middle"],
		"above": ["stock exchange"],
		"below": ["lake shore dr"]
	},
	"indiana ave": {
		"type": "property",
		"quality": "red",
		"rent": [18, 90, 250, 700, 875, 1050, 1700],
		"mortgage": 110,
		"house": 150,
		"forward": ["illinois ave"],
		"backward": ["chance middle north"],
		"side": "top",
		"track": ["middle"],
		"above": ["wall st"],
		"below": ["michigan ave"]
	},
	"illinois ave": {
		"type": "property",
		"quality": "red",
		"rent": [20, 100, 300, 750, 925, 1100, 1750],
		"mortgage": 120,
		"house": 150,
		"forward": ["b&o railroad"],
		"backward": ["indiana ave"],
		"side": "top",
		"track": ["middle"],
		"above": ["tax refund"],
		"below": ["yellow cab co"]
	},
	"atlantic ave": {
		"type": "property",
		"quality": "yellow",
		"rent": [22, 110, 330, 800, 975, 1150, 1850],
		"mortgage": 130,
		"house": 150,
		"forward": ["ventnor ave"],
		"backward": ["b&o railroad"],
		"side": "top",
		"track": ["middle"],
		"above": ["chance inner ne"],
		"below": ["community chest outer north"]
	},
	"ventnor ave": {
		"type": "property",
		"quality": "yellow",
		"rent": [22, 110, 330, 800, 975, 1150, 1850],
		"mortgage": 130,
		"house": 150,
		"forward": ["water works"],
		"backward": ["atlantic ave"],
		"side": "top",
		"track": ["middle"],
		"above": ["florida ave"],
		"below": ["south temple"]
	},
	"marvin gardens": {
		"type": "property",
		"quality": "yellow",
		"rent": [24, 120, 360, 850, 1025, 1200, 1900],
		"mortgage": 140,
		"house": 150,
		"forward": ["roll3"],
		"backward": ["water works"],
		"side": "top",
		"track": ["middle"],
		"above": ["holland tunnel ne"],
		"below": ["trash collector"]
	},
	"pacific ave": {
		"type": "property",
		"quality": "green",
		"rent": [26, 120, 390, 900, 1100, 1275, 2050],
		"mortgage": 150,
		"house": 200,
		"forward": ["north carolina ave"],
		"backward": ["roll3"],
		"side": "right",
		"track": ["middle"],
		"above": ["holland tunnel ne"],
		"below": ["walnut st"]
	},
	"north carolina ave": {
		"type": "property",
		"quality": "green",
		"rent": [26, 120, 390, 900, 1100, 1275, 2050],
		"mortgage": 150,
		"house": 200,
		"forward": ["community chest middle east"],
		"backward": ["pacific ave"],
		"side": "right",
		"track": ["middle"],
		"above": ["holland tunnel ne"],
		"below": ["community chest outer east"]
	},
	"pennsylvania ave": {
		"type": "property",
		"quality": "green",
		"rent": [28, 150, 450, 1000, 1200, 1400, 2200],
		"mortgage": 160,
		"house": 200,
		"forward": ["short line"],
		"backward": ["community chest middle east"],
		"side": "right",
		"track": ["middle"],
		"above": ["biscayne ave"],
		"below": ["bus ticket east"]
	},
	"park pl": {
		"type": "property",
		"quality": "blue",
		"rent": [35, 175, 500, 1100, 1300, 1500, 2400],
		"mortgage": 175,
		"house": 200,
		"forward": ["luxury tax"],
		"backward": ["chance middle east"],
		"side": "right",
		"track": ["middle"],
		"above": ["lombard st"],
		"below": ["birthday gift"]
	},
	"boardwalk": {
		"type": "property",
		"quality": "blue",
		"rent": [50, 200, 600, 1400, 1700, 2000, 3200],
		"mortgage": 200,
		"house": 200,
		"forward": ["go"],
		"backward": ["luxury tax"],
		"side": "right",
		"track": ["middle"],
		"above": ["squeeze play"],
		"below": ["ventura blvd"]
	},
	"checker cab co": {
		"type": "transportation",
		"quality": "cab",
		"rent": [30, 60, 120, 240],
		"mortgage": 150,
		"forward": ["reading railroad"],
		"backward": ["bus ticket south"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["income tax"]
	},
	"black & white cab co": {
		"type": "transportation",
		"quality": "cab",
		"rent": [30, 60, 120, 240],
		"mortgage": 150,
		"forward": ["dekalb ave"],
		"backward": ["chance outer west"],
		"side": "left",
		"track": ["outer"],
		"above": ["st james pl"]
	},
	"yellow cab co": {
		"type": "transportation",
		"quality": "cab",
		"rent": [30, 60, 120, 240],
		"mortgage": 150,
		"forward": ["b&o railroad"],
		"backward": ["michigan ave"],
		"side": "top",
		"track": ["outer"],
		"above": ["illinois ave"]
	},
	"ute cab co": {
		"type": "transportation",
		"quality": "cab",
		"rent": [30, 60, 120, 240],
		"mortgage": 150,
		"forward": ["birthday gift"],
		"backward": ["sewage system"],
		"side": "right",
		"track": ["middle"],
		"above": ["chance middle east"]
	},
	"water works": {
		"type": "utility",
		"quality": "utility",
		"multiplier": [10, 20, 40, 80, 100, 120, 150],
		"mortgage": 75,
		"forward": ["marvin gardens"],
		"backward": ["ventnor ave"],
		"side": "top",
		"track": ["middle"],
		"above": ["holland tunnel ne"],
		"below": ["west temple"]
	},
	"cable company": {
		"type": "utility",
		"quality": "utility",
		"multiplier": [10, 20, 40, 80, 100, 120, 150],
		"mortgage": 75,
		"forward": ["magazine st"],
		"backward": ["chance outer south"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["connecticut ave"]
	},
	"electric company": {
		"type": "utility",
		"quality": "utility",
		"multiplier": [10, 20, 40, 80, 100, 120, 150],
		"mortgage": 75,
		"forward": ["states ave"],
		"backward": ["st charles pl"],
		"side": "left",
		"track": ["middle"],
		"above": ["bonus"],
		"below": ["internet service provider"]
	},
	"internet service provider": {
		"type": "utility",
		"quality": "utility",
		"multiplier": [10, 20, 40, 80, 100, 120, 150],
		"mortgage": 75,
		"forward": ["westheimer rd"],
		"backward": ["kirby dr"],
		"side": "left",
		"track": ["outer"],
		"above": ["electric company"]
	},
	"gas company": {
		"type": "utility",
		"quality": "utility",
		"multiplier": [10, 20, 40, 80, 100, 120, 150],
		"mortgage": 75,
		"forward": ["chance inner ne"],
		"backward": ["tax refund"],
		"side": "top",
		"track": ["inner"],
		"below": ["b&o railroad"]
	},
	"telephone company": {
		"type": "utility",
		"quality": "utility",
		"multiplier": [10, 20, 40, 80, 100, 120, 150],
		"mortgage": 75,
		"forward": ["community chest inner sw"],
		"backward": ["fisherman's wharf"],
		"side": "bottom",
		"track": ["inner"],
		"below": ["reading railroad"]
	},
	"trash collector": {
		"type": "utility",
		"quality": "utility",
		"multiplier": [10, 20, 40, 80, 100, 120, 150],
		"mortgage": 75,
		"forward": ["north temple"],
		"backward": ["west temple"],
		"side": "top",
		"track": ["outer"],
		"above": ["marvin gardens"]
	},
	"sewage system": {
		"type": "utility",
		"quality": "utility",
		"multiplier": [10, 20, 40, 80, 100, 120, 150],
		"mortgage": 75,
		"forward": ["ute cab co"],
		"backward": ["bus ticket east"],
		"side": "right",
		"track": ["outer"],
		"above": ["short line"]
	},
	"reading railroad": {
		"type": "transportation",
		"quality": "railroad",
		"rent": [25, 50, 100, 200],
		"mortgage": 100,
		"forward": ["oriental ave", "esplanade ave"],
		"backward": ["income tax", "checker cab co"],
		"side": "bottom",
		"track": ["middle", "outer"],
		"above": ["telephone company"]
	},
	"pennsylvania railroad": {
		"type": "transportation",
		"quality": "railroad",
		"rent": [25, 50, 100, 200],
		"mortgage": 100,
		"forward": ["st james pl", "fifth ave"],
		"backward": ["virginia ave", "newbury st"],
		"side": "left",
		"track": ["middle", "inner"],
		"below": ["chance outer west"]
	},
	"b&o railroad": {
		"type": "transportation",
		"quality": "railroad",
		"rent": [25, 50, 100, 200],
		"mortgage": 100,
		"forward": ["atlantic ave", "community chest outer north"],
		"backward": ["illinois ave", "yellow cab co"],
		"side": "top",
		"track": ["middle", "outer"],
		"above": ["gas company"]
	},
	"short line": {
		"type": "transportation",
		"quality": "railroad",
		"rent": [25, 50, 100, 200],
		"mortgage": 100,
		"forward": ["chance middle east", "reverse"],
		"backward": ["pennsylvania ave", "biscayne ave"],
		"side": "right",
		"track": ["middle", "inner"],
		"below": ["sewage system"]
	},
	"holland tunnel ne": {
		"type": "tunnel",
		"forward": ["miami ave"],
		"backward": ["florida ave"],
		"side": "edge",
		"track": ["inner"],
		"below": ["roll3", "water works", "marvin gardens", "pacific ave", "north carolina ave"]
	},
	"holland tunnel sw": {
		"type": "tunnel",
		"forward": ["auction"],
		"backward": ["bourbon st"],
		"side": "edge",
		"track": ["outer"],
		"above": ["jail"]
	},
	"chance inner ne": {
		"type": "chance",
		"forward": ["florida ave"],
		"backward": ["gas company"],
		"side": "top",
		"track": ["inner"],
		"below": ["atlantic ave"]
	},
	"chance outer west": {
		"type": "chance",
		"forward": ["black & white cab co"],
		"backward": ["cullen blvd"],
		"side": "left",
		"track": ["outer"],
		"above": ["pennsylvania railroad"]
	},
	"chance outer nw": {
		"type": "chance",
		"forward": ["lake shore dr"],
		"backward": ["randolph st"],
		"side": "top",
		"track": ["outer"],
		"above": ["free parking"]
	},
	"chance outer south": {
		"type": "chance",
		"forward": ["cable company"],
		"backward": ["canal st"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["vermont ave"]
	},
	"chance outer se": {
		"type": "chance",
		"forward": ["rodeo dr"],
		"backward": ["ventura blvd"],
		"side": "right",
		"track": ["outer"],
		"above": ["go"]
	},
	"chance middle east": {
		"type": "chance",
		"forward": ["park pl"],
		"backward": ["short line"],
		"side": "right",
		"track": ["middle"],
		"above": ["reverse"],
		"below": ["ute cab co"]
	},
	"chance middle south": {
		"type": "chance",
		"forward": ["vermont ave"],
		"backward": ["oriental ave"],
		"side": "bottom",
		"track": ["middle"],
		"above": ["beacon st"],
		"below": ["canal st"]
	},
	"chance middle north": {
		"type": "chance",
		"forward": ["indiana ave"],
		"backward": ["kentucky ave"],
		"side": "top",
		"track": ["middle"],
		"above": ["stock exchange"],
		"below": ["wacker dr"]
	},
	"squeeze play": {
		"type": "squeeze play",
		"forward": ["the embarcadero"],
		"backward": ["lombard st"],
		"side": "edge",
		"track": ["inner"],
		"below": ["go", "luxury tax", "boardwalk", "mediterranean ave", "community chest middle south"]
	},
	"reverse": {
		"type": "reverse",
		"forward": ["lombard st"],
		"backward": ["short line"],
		"side": "right",
		"track": ["inner"],
		"below": ["chance middle east"]
	},
	"bonus": {
		"type": "pay",
		"forward": ["boylston st"],
		"backward": ["beacon st"],
		"side": "edge",
		"track": ["inner"],
		"below": ["jail", "electric company", "st charles pl", "connecticut ave", "vermont ave"]
	},
	"pay day": {
		"type": "pay",
		"forward": ["randolph st"],
		"backward": ["peachtree st"],
		"side": "edge",
		"track": ["outer"],
		"above": ["free parking"]
	},
	"community chest inner sw": {
		"type": "community chest",
		"forward": ["beacon st"],
		"backward": ["telephone company"],
		"side": "bottom",
		"track": ["inner"],
		"below": ["oriental ave"]
	},
	"community chest outer se": {
		"type": "community chest",
		"forward": ["nicollet ave"],
		"backward": ["lake st"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["go"]
	},
	"community chest outer nw": {
		"type": "community chest",
		"forward": ["young int'l blvd"],
		"backward": ["dekalb ave"],
		"side": "left",
		"track": ["outer"],
		"above": ["tennessee ave"]
	},
	"community chest outer north": {
		"type": "community chest",
		"forward": ["south temple"],
		"backward": ["b&o railroad"],
		"side": "top",
		"track": ["outer"],
		"above": ["atlantic ave"],
	},
	"community chest outer east": {
		"type": "community chest",
		"forward": ["market st"],
		"backward": ["walnut st"],
		"side": "right",
		"track": ["outer"],
		"above": ["north carolina ave"]
	},
	"community chest middle south": {
		"type": "community chest",
		"forward": ["baltic ave"],
		"backward": ["mediterranean ave"],
		"side": "bottom",
		"track": ["middle"],
		"above": ["squeeze play"],
		"below": ["hennepin ave"]
	},
	"community chest middle west": {
		"type": "community chest",
		"forward": ["tennessee ave"],
		"backward": ["st james pl"],
		"side": "left",
		"track": ["middle"],
		"above": ["madison ave"],
		"below": ["dekalb ave"]
	},
	"community chest middle east": {
		"type": "community chest",
		"forward": ["pennsylvania ave"],
		"backward": ["north carolina ave"],
		"side": "right",
		"track": ["middle"],
		"above": ["miami ave"],
		"below": ["market st"]
	},
	"stock exchange": {
		"type": "spot",
		"forward": ["wall st"],
		"backward": ["madison ave"],
		"side": "edge",
		"track": ["inner"],
		"below": ["free parking", "chance", "kentucky ave", "new york ave", "tennessee ave"]
	},
	"tax refund": {
		"type": "spot",
		"forward": ["gas company"],
		"backward": ["wall st"],
		"side": "top",
		"track": ["inner"],
		"below": ["illinois ave"]
	},
	"subway": {
		"type": "subway",
		"forward": ["lake st"],
		"backward": ["rodeo dr"],
		"side": "edge",
		"track": ["outer"],
		"above": ["go"]
	},
	"bus ticket south": {
		"type": "bus",
		"forward": ["checker cab co"],
		"backward": ["hennepin ave"],
		"side": "bottom",
		"track": ["outer"],
		"above": ["baltic ave"]
	},
	"bus ticket east": {
		"type": "bus",
		"forward": ["sewage system"],
		"backward": ["ute cab co"],
		"side": "right",
		"track": ["outer"],
		"above": ["pennsylvania ave"]
	},
	"auction": {
		"type": "auction",
		"forward": ["katy freeway"],
		"backward": ["holland tunnel sw"],
		"side": "left",
		"track": ["outer"],
		"above": ["jail"]
	},
	"go to jail": {
		"type": "spot",
		"forward": ["south st"],
		"backward": ["temple square"],
		"side": "edge",
		"track": ["outer"],
		"above": ["roll3"]
	},
	"jail": {
		"type": "spot",
		"forward": ["st charles pl"],
		"backward": ["connecticut ave"],
		"side": "edge",
		"track": ["middle"],
		"above": ["bonus"],
		"below": ["holland tunnel sw", "katy freeway", "auction", "bourbon st", "magazine st"]
	},
	"birthday gift": {
		"type": "spot",
		"forward": ["mulholland dr"],
		"backward": ["ute cab co"],
		"side": "right",
		"track": ["outer"],
		"above": ["park pl"],
	},
	"income tax": {
		"type": "spot",
		"forward": ["reading railroad"],
		"backward": ["baltic ave"],
		"side": "bottom",
		"track": ["middle"],
		"above": ["fisherman's wharf"],
		"below": ["checker cab co"]
	},
	"go": {
		"type": "pay",
		"forward": ["mediterranean ave"],
		"backward": ["boardwalk"],
		"side": "edge",
		"track": ["middle"],
		"above": ["squeeze play"],
		"below": ["subway", "chance outer se", "rodeo dr", "lake st", "community chest outer se"]
	},
	"free parking": {
		"type": "spot",
		"forward": ["kentucky ave"],
		"backward": ["new york ave"],
		"side": "edge",
		"track": ["middle"],
		"above": ["stock exchange"],
		"below": ["pay day", "chance outer nw", "randolph st", "peachtree st", "decatur st"]
	},
	"roll3": {
		"type": "spot",
		"forward": ["pacific ave"],
		"backward": ["marvin gardens"],
		"side": "edge",
		"track": ["middle"],
		"above": ["holland tunnel ne"],
		"below": ["go to jail", "north temple", "temple square", "south st", "broad st"]
	},
	"luxury tax": {
		"type": "spot",
		"forward": ["boardwalk"],
		"backward": ["park pl"],
		"side": "right",
		"track": ["middle"],
		"above": ["squeeze play"],
		"below": ["mulholland dr"]
	}
}